import type { Metadata } from "next";

import Scanner from "@/components/Scanner";
import { css } from "@panda/css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h1 className={css({ fontSize: "4xl" })}>SCC 自習室 入退室管理</h1>
        <main>
          <div className={css({ display: "flex" })}>
            <Scanner />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
