import type { Metadata } from "next";
import Link from "next/link";

import { BIZ_UDPGothic } from "@next/font/google";

import Scanner from "@/components/Scanner";
import { css } from "@panda/css";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bizUDPGpthic = BIZ_UDPGothic({
  weight: ["400"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={bizUDPGpthic.className}>
        <header>
          <h1 className={css({ fontSize: "4xl" })}>Roomkeeper</h1>
        </header>
        <div>
          <Link href="/">スキャン</Link>
          <Link href="/history">履歴</Link>
        </div>
        <main>
          <div className={css({ display: "flex" })}>
            <Scanner />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
